/**
 * Field limits from the backend OpenAPI contract.
 *
 * AUTO-GENERATED by scripts/sync-api/generate-validation-rules.ts — do not
 * hand-edit; rerun scripts/sync-api/sync-api.sh to refresh from the contract.
 *
 * Forms block submits that would 400 (note: name, fact title and fact content
 * also require at least 1 character); the Foundry document sync clamps
 * instead (an oversized Foundry document must not break the sync).
 */
export const CHARACTER_NAME_MAX_LENGTH = 50;
export const KNOW_DESCRIPTION_MAX_LENGTH = 256;
export const FACT_TITLE_MAX_LENGTH = 100;
export const FACT_CONTENT_MAX_LENGTH = 3000;

/** Clamp a string to the given contract limit (used by the Foundry sync). */
export function clampToLength(value: string, maxLength: number): string {
  return value.length <= maxLength ? value : value.slice(0, maxLength);
}
